name: Deploy Documentation

on:
  push:
    branches:
      - develop

jobs:
  deploy_docs:
    if: ${{ github.repository == 'ChuckerTeam/chucker'}}
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate docs
        run: ./assemble_docs.sh